/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SendRouteImport } from './routes/send'
import { Route as DlqRouteImport } from './routes/dlq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CohortsRouteImport } from './routes/cohorts'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as BulkUploadRouteImport } from './routes/bulk-upload'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const DlqRoute = DlqRouteImport.update({
  id: '/dlq',
  path: '/dlq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CohortsRoute = CohortsRouteImport.update({
  id: '/cohorts',
  path: '/cohorts',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkUploadRoute = BulkUploadRouteImport.update({
  id: '/bulk-upload',
  path: '/bulk-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/bulk-upload': typeof BulkUploadRoute
  '/campaigns': typeof CampaignsRoute
  '/cohorts': typeof CohortsRoute
  '/dashboard': typeof DashboardRoute
  '/dlq': typeof DlqRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/bulk-upload': typeof BulkUploadRoute
  '/campaigns': typeof CampaignsRoute
  '/cohorts': typeof CohortsRoute
  '/dashboard': typeof DashboardRoute
  '/dlq': typeof DlqRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/bulk-upload': typeof BulkUploadRoute
  '/campaigns': typeof CampaignsRoute
  '/cohorts': typeof CohortsRoute
  '/dashboard': typeof DashboardRoute
  '/dlq': typeof DlqRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-keys'
    | '/bulk-upload'
    | '/campaigns'
    | '/cohorts'
    | '/dashboard'
    | '/dlq'
    | '/send'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-keys'
    | '/bulk-upload'
    | '/campaigns'
    | '/cohorts'
    | '/dashboard'
    | '/dlq'
    | '/send'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/api-keys'
    | '/bulk-upload'
    | '/campaigns'
    | '/cohorts'
    | '/dashboard'
    | '/dlq'
    | '/send'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiKeysRoute: typeof ApiKeysRoute
  BulkUploadRoute: typeof BulkUploadRoute
  CampaignsRoute: typeof CampaignsRoute
  CohortsRoute: typeof CohortsRoute
  DashboardRoute: typeof DashboardRoute
  DlqRoute: typeof DlqRoute
  SendRoute: typeof SendRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dlq': {
      id: '/dlq'
      path: '/dlq'
      fullPath: '/dlq'
      preLoaderRoute: typeof DlqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cohorts': {
      id: '/cohorts'
      path: '/cohorts'
      fullPath: '/cohorts'
      preLoaderRoute: typeof CohortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-upload': {
      id: '/bulk-upload'
      path: '/bulk-upload'
      fullPath: '/bulk-upload'
      preLoaderRoute: typeof BulkUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiKeysRoute: ApiKeysRoute,
  BulkUploadRoute: BulkUploadRoute,
  CampaignsRoute: CampaignsRoute,
  CohortsRoute: CohortsRoute,
  DashboardRoute: DashboardRoute,
  DlqRoute: DlqRoute,
  SendRoute: SendRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
